### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by zarmstrong**
Change confusingboat to zacharmstrong for dockerhub. My build uses the latest code as of 4/2/22

### CODE REVIEW

**Comment by zarmstrong** [comment]
Fixes #37 
Fixes #38

**Comment by zarmstrong** [comment]
Added example docker-compose

**Comment by Chopp3rDave** [comment]
@Fabbi Can we get this merged?

**Comment by Fabbi** [comment]
Have you tested it? I didn't have the time to yet.

**Comment by zarmstrong** [comment]
prob doesnt matter since you weren't asking me and already merged anyway, but yeah, I've been using my fork in the docker-container since around when I submitted the merge request (4 May)

**Comment by Fabbi** [comment]
😃 Yeah, I wanted to work on the code either way so I just merged it. 
I'm implementing better key sources atm.

Thanks for your PR and patience 😅

**Comment by zarmstrong** [comment]
No worries! Love this project and wanted to help where I could!

**Pull request merged**
