### PR TITLE
Fix Tiny Tina's Wonderlands code parsing for all platforms

### PR DESCRIPTION
**Pull request by therobd**
The Tiny Tina's Wonderlands page (http://orcz.com/Tiny_Tina%27s_Wonderlands:_Shift_Codes) has a different format for its SHiFT codes than the other Borderlands pages (e.g. http://orcz.com/Borderlands_2:_Golden_Key) due to its codes being universal. Instead of listing a code for each platform, it lists a code and then whether it works on each platform.

For the moment, these codes work on all platforms, so if a code is present and non-expired in a row, we can return that the code is compatible for all platforms.

### CODE REVIEW

**Comment by therobd** [comment]
Fixes Issue #39.

**Comment by Chopp3rDave** [comment]
@Fabbi Can we get this merged?

**Comment by therobd** [comment]
I've switched to https://github.com/jauderho/bl3auto/, as the source for the TTW codes (http://orcz.com/Tiny_Tina%27s_Wonderlands:_Shift_Codes) is not kept up-to-date. bl3auto uses a site that automatically updates when a new code is released.

**Comment by Chopp3rDave** [comment]
> I've switched to https://github.com/jauderho/bl3auto/, as the source for the TTW codes (http://orcz.com/Tiny_Tina%27s_Wonderlands:_Shift_Codes) is not kept up-to-date. bl3auto uses a site that automatically updates when a new code is released.

Thanks, headed over!

**Comment by Fabbi** [comment]
Yeah I've wanted to change my code to use another source, too. 
In fact the c++ GUI version of this tool does do so already, but I hadn't had the time to properly split both versions so the GUI version is kind of hidden away in a branch still.

**Comment by Fabbi** [comment]
@Chopp3rDave @therobd I just pushed a new version that uses orcicorn as source and is able to auto detect new SHIFT-games / platforms.

**Pull request closed without merging**
